# Generated by Django 3.0 on 2019-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0003_auto_20191212_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='post',
            field=models.TextField(max_length=150),
        ),
    ]
