# Generated by Django 3.0 on 2019-12-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0004_auto_20191212_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
