# Generated by Django 3.0 on 2019-12-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0006_auto_20191213_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pics',
            old_name='image_cover',
            new_name='cover',
        ),
    ]
