# Generated by Django 3.0 on 2019-12-13 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0007_auto_20191213_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
