# Generated by Django 3.0 on 2019-12-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0008_auto_20191213_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
